apiVersion: v1
kind: Namespace
metadata:
  name: apollo-demo
  labels:
    app.kubernetes.io/name: apollo-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: federation-demo
  labels:
    app.kubernetes.io/name: federation-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-demo
  labels:
    app.kubernetes.io/name: kafka-demo
